# Generated by Django 3.2.14 on 2022-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('place', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
