# Generated by Django 3.2.14 on 2022-08-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0002_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='map',
        ),
    ]
